---
title: "Voting-Frederick"
author: "Wells"
date: "2026-05-19"
output: html_document
---
We talked with Katelynn when she visited us about a project looking at election data.

```{r}
library(tidyverse)
library(readxl)
library(googlesheets4)
library(googledrive)
```
#GENERAL_11PG24_Prov_CVR_SBE - 1
```{r}
gs4_deauth()

general1 <- read_sheet("https://docs.google.com/spreadsheets/d/131vpseVIqOyGPz7zRuFr2d-89QegYDW9XPWyk-2vsMs/edit?usp=sharing")

write_csv(general1, "./data/GENERAL_11PG24_Prov_CVR_SBE_1.csv")
```

```{r}

primary <- read_excel("/Users/robwells/Library/CloudStorage/GoogleDrive-robwells@umd.edu/My Drive/DJNF 2026/Katelynn Winebrenner/2024 Cast Vote Record/PRIMARY_11PP24_Prov_CVR_SBE.xlsx")


write_csv(primary, "./data/PRIMARY_11PP24_Prov_CVR_SBE.csv")
```


```{r}
general2 <- read_excel("/Users/robwells/Library/CloudStorage/GoogleDrive-robwells@umd.edu/My Drive/DJNF 2026/Katelynn Winebrenner/2024 Cast Vote Record/PRIMARY_11PP24_Prov_CVR_SBE.xlsx")


write_csv(general2, "./data/GENERAL_11PG24_Prov_CVR_SBE.csv")
```

```{r}
gs4_deauth()
library(googledrive)
library(readr)

# Tell the googledrive package to access files publicly (matching your gs4_deauth)
drive_deauth()

# Download the file locally
drive_download(
  file = "https://drive.google.com/file/d/1Ipevjtn-MdnOVXM8-AXXid9dzTQFMwUb/view?usp=sharing",
  path = "general1.csv",
  overwrite = TRUE
)

# Read the local CSV file
general1 <- read_csv("general1.csv")



```
```{r}
# Download the file locally
drive_download(
  file = "https://drive.google.com/file/d/151_wMKcmzyf821rNIWEsiOE6XLSGb1Tb/view?usp=sharing",
  path = "general2.csv",
  overwrite = TRUE
)

# Read the local CSV file
general2 <- read_csv("general2.csv")
```
```{r}
# Download the file locally
drive_download(
  file = "https://drive.google.com/file/d/1bKVAeKb4cbsZQe0TXxAVWWTLtl6Q1XDr/view?usp=sharing",
  path = "primary.csv",
  overwrite = TRUE
)

# Read the local CSV file
primary <- read_csv("primary.csv")
```
