---
title: "Hispanic Student Attendance of Maryland Public Schools 2020-2026 - Will Hammann"
author: "Wells"
date: "2026-05-25"
output: html_document
---

# load libraries
```{r}
install.packages("tidycensus")
library(tidyverse)
library(tidycensus)
library(janitor)
library(dplyr)
```

#load and clean data
```{r}
#2020-2022 used lss name instead of lea name so it needs renamed to be continuous

data_2020<-read_csv("../data/Enrollment_By_Race_2020.csv") |>
     clean_names() |>
     rename(lea = lss, lea_name = lss_name)

data_2021<-read_csv("../data/Enrollment_By_Race_2021.csv") |>
     clean_names() |> 
     rename(lea = lss, lea_name = lss_name)

data_2022<-read_csv("../data/Enrollment_By_Race_2022.csv") |>
     clean_names() |>
     rename(lea = lss, lea_name = lss_name)

data_2023<-read_csv("../data/Enrollment_By_Race_2023.csv") |>
     clean_names()
data_2024<-read_csv("../data/Enrollment_By_Race_2024.csv") |>
     clean_names()
data_2025<-read_csv("../data/Enrollment_By_Race_2025.csv") |>
     clean_names()
data_2026<-read_csv("../data/Enrollment_By_Race_2026.csv") |>
     clean_names()

data_2020$enrolled_count[data_2020$enrolled_count == '*'] <- NA
data_2021$enrolled_count[data_2021$enrolled_count == '*'] <- NA
data_2022$enrolled_count[data_2022$enrolled_count == '*'] <- NA
data_2023$enrolled_count[data_2023$enrolled_count == '*'] <- NA
data_2024$enrolled_count[data_2024$enrolled_count == '*'] <- NA
data_2025$enrolled_count[data_2025$enrolled_count == '*'] <- NA
data_2026$enrolled_count[data_2026$enrolled_count == '*'] <- NA

data_2020$enrolled_count <- as.numeric(data_2020$enrolled_count)
data_2021$enrolled_count <- as.numeric(data_2021$enrolled_count)
data_2022$enrolled_count <- as.numeric(data_2022$enrolled_count)
data_2023$enrolled_count <- as.numeric(data_2023$enrolled_count)
data_2024$enrolled_count <- as.numeric(data_2024$enrolled_count)
data_2025$enrolled_count <- as.numeric(data_2025$enrolled_count)
data_2026$enrolled_count <- as.numeric(data_2026$enrolled_count)
```

#Combine into one dataframe
```{r}

all_data <- rbind(data_2020, data_2021, data_2022, data_2023, data_2024, data_2025, data_2026)

```

## Deaths By State for Children

```{r}
options(scipen = 999)  # Disable scientific notation globally

children |> 
group_by(state) |> 
  summarize(
    Deaths = sum(victims_killed)
  ) |> 
  arrange(state)

```

## Deaths By State for Teens
```{r}

teens |> 
group_by(state) |> 
  summarize(
    Deaths = sum(victims_killed)
  ) |> 
  arrange(state)
```

## Arrests for One City or County for Deaths Involving Children
```{r}
children |> 
  filter(city_or_county == "Baton Rouge") |> 
  group_by(city_or_county) |>
  summarize(
    Arrests = sum(suspects_arrested)
  ) |> 
  arrange(desc(Arrests))

```

## Deaths for One State and City or County for Deaths Involving Teens
```{r}
teens |> 
  filter(state == "Maryland") |> 
  filter(city_or_county == "Baltimore") |> 
  group_by(city_or_county) |>
  summarize(
    Deaths = sum(victims_killed)
  ) |> 
  arrange(desc(Deaths))

```
