---
title: "Government Spending Master DJNF"
author: "Wells"
date: "2026-05-15"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(tidycensus)
library(janitor)
```

#load spending data
```{r}

spending <- read_csv("../data/federal_spending_by_county_2020 2024 rob_0416_v2.csv") |> 
     clean_names()

```

**pokin around!**

## Spending by agency

```{r}
options(scipen = 999)  # Disable scientific notation globally

spending |> 
group_by(agency) |> 
  summarize(
    n = n(),
    total_spent = sum(spending_total, na.rm = TRUE)
  ) |> 
  arrange(desc(total_spent))

```

## Spending by state

```{r}
spending |> 
group_by(state_nm) |> 
  summarize(
    n = n(),
    total_spent = sum(spending_total, na.rm = TRUE)
  ) |> 
  arrange(desc(total_spent))

```

## Spending by city
```{r}
spending |> 
group_by(cty_name, state_nm) |> 
  summarize(
     total_spent = sum(spending_total, na.rm = TRUE),
     n = n()
  ) |> 
  arrange(desc(total_spent))

```

## Highlight specific city
```{r}

spending |> 
  filter(cty_name == "HENNEPIN") |> 
  group_by(agency) |> 
  summarize(
     total_spent = sum(spending_total, na.rm = TRUE),
     n = n()
  ) |> 
  arrange(desc(total_spent))
```

## Highlight specific city and agency
```{r}
spending |> 
  filter(cty_name == "HENNEPIN") |> 
  filter(agency == "Department of Health and Human Services") |> 
  select(fyear, cty_name, spending_total)
```

