---
title: "Voting-Frederick"
author: "Wells"
date: "2026-05-19"
output: html_document
---
We talked with Katelynn when she visited us about a project looking at election data.

```{r}
library(tidyverse)
library(readxl)
library(googlesheets4)
library(googledrive)
library(janitor)
```
#Import data
```{r}

general1 <- read_csv("https://raw.githubusercontent.com/djnf-data-2026/master/refs/heads/main/data/GENERAL_11PG24_Prov_CVR_SBE_1.csv") |> 
  clean_names()


general2 <- read_csv("https://raw.githubusercontent.com/djnf-data-2026/master/refs/heads/main/data/GENERAL_11PG24_Prov_CVR_SBE.csv") |> 
  clean_names()

primary <- read_csv("https://raw.githubusercontent.com/djnf-data-2026/master/refs/heads/main/data/PRIMARY_11PP24_Prov_CVR_SBE.csv") |> 
  clean_names()

```

# Pokin around

```{r}
precincts <- primary |> 
  group_by(precinct) |> 
  count()

#write_csv(precincts, "../data/precincts.csv")
```



```{r}
top <- primary |> 
  group_by(precinct) |> 
  count(
    dem_president_of_the_united_states_6_500001630106, 
    rep_president_of_the_united_states_6_500001630206
  ) |> 
  filter(
    dem_president_of_the_united_states_6_500001630106 == "Joe Biden (10066066.0000254)" | 
    rep_president_of_the_united_states_6_500001630206 == "Donald J. Trump (10066066.0000246)"
  ) |> 
  pivot_longer(
    cols = c(
      dem_president_of_the_united_states_6_500001630106, 
      rep_president_of_the_united_states_6_500001630206
    ),
    names_to = "candidate_type",  # Changed from "precinct" to avoid clashing
    values_to = "candidate_name", # Moves the actual name strings here
    values_drop_na = TRUE         # Optional: Drops the messy 'NA' rows seen in your output
  )
  



```


Wider
```{r}

top_wide <- primary |> 
  group_by(precinct) |> 
  count(
    dem_president_of_the_united_states_6_500001630106, 
    rep_president_of_the_united_states_6_500001630206
  ) |> 
  filter(
    dem_president_of_the_united_states_6_500001630106 == "Joe Biden (10066066.0000254)" | 
    rep_president_of_the_united_states_6_500001630206 == "Donald J. Trump (10066066.0000246)"
  ) |> 
  mutate(candidate = coalesce(
    dem_president_of_the_united_states_6_500001630106, 
    rep_president_of_the_united_states_6_500001630206
  )) |> 
  # 2. Pivot wider using 'id_cols' to force exactly one row per precinct
  pivot_wider(
    id_cols = precinct,
    names_from = candidate,
    values_from = n
  ) |> 
  rename(Biden = 2, Trump =3)

```


Chart
```{r}
top_wide |> 
  # 1. Pivot the columns back to long format for ggplot
  pivot_longer(
    cols = -precinct, 
    names_to = "candidate", 
    values_to = "votes"
  ) |> 
  # 2. Clean up the messy, long ID numbers from the candidate names
  mutate(candidate = case_when(
    stringr::str_detect(candidate, "Biden") ~ "Joe Biden",
    stringr::str_detect(candidate, "Trump") ~ "Donald Trump",
    TRUE ~ candidate
  )) |> 
  # 3. Plot with fill mapped to candidate
  ggplot(aes(x = precinct, y = votes, fill = candidate)) +
  geom_col(position = "dodge") +
  labs(
    title = "Candidate votes",
    caption = "Graphic by Rob Wells, 12-22-19",
    y = "Votes",
    x = "Precinct",
    fill = "Candidate" # Adds a clean title to the legend
  ) +
  theme_minimal()

```




# Wrangling to get it into R

#GENERAL_11PG24_Prov_CVR_SBE - 1
```{r}
general1 <- read_excel("/Users/gizmofo/Library/CloudStorage/GoogleDrive-robwells@umd.edu/My Drive/DJNF 2026/Katelynn Winebrenner/2024 Cast Vote Record/GENERAL_11PG24_Prov_CVR_SBE - 1.xlsx")

write_csv(general1, "../data/GENERAL_11PG24_Prov_CVR_SBE_1.csv")
```

GENERAL_11PG24_Prov_CVR_SBE
```{r}
general2 <- read_excel("/Users/gizmofo/Library/CloudStorage/GoogleDrive-robwells@umd.edu/My Drive/DJNF 2026/Katelynn Winebrenner/2024 Cast Vote Record/GENERAL_11PG24_Prov_CVR_SBE.xlsx")


write_csv(general2, "../data/GENERAL_11PG24_Prov_CVR_SBE.csv")
```

PRIMARY_11PP24_Prov_CVR_SBE
```{r}

primary <- read_excel("/Users/gizmofo/Library/CloudStorage/GoogleDrive-robwells@umd.edu/My Drive/DJNF 2026/Katelynn Winebrenner/2024 Cast Vote Record/PRIMARY_11PP24_Prov_CVR_SBE.xlsx")


write_csv(primary, "../data/PRIMARY_11PP24_Prov_CVR_SBE.csv")
```







```{r}
gs4_deauth()
library(googledrive)
library(readr)

# Tell the googledrive package to access files publicly (matching your gs4_deauth)
drive_deauth()

# Download the file locally
drive_download(
  file = "https://drive.google.com/file/d/1Ipevjtn-MdnOVXM8-AXXid9dzTQFMwUb/view?usp=sharing",
  path = "general1.csv",
  overwrite = TRUE
)

# Read the local CSV file
general1 <- read_csv("general1.csv")



```
```{r}
# Download the file locally
drive_download(
  file = "https://drive.google.com/file/d/151_wMKcmzyf821rNIWEsiOE6XLSGb1Tb/view?usp=sharing",
  path = "general2.csv",
  overwrite = TRUE
)

# Read the local CSV file
general2 <- read_csv("general2.csv")
```
```{r}
# Download the file locally
drive_download(
  file = "https://drive.google.com/file/d/1bKVAeKb4cbsZQe0TXxAVWWTLtl6Q1XDr/view?usp=sharing",
  path = "primary.csv",
  overwrite = TRUE
)

# Read the local CSV file
primary <- read_csv("primary.csv")
```
